# Status Bar: waybar
#
# Read `man 5 sway-bar` for more information about this section.
# Read `man 5 waybar` for more information about the waybar instance style and layout configuration
#
# Requires: waybar

bar {
    id 1
    output *
    position top
    swaybar_command waybar
    #font 'Monocraft 10'
    #tray_output none

    colors {
        background #222222
        statusline #BD93F9
        separator  #44475A

        focused_workspace  #222222 #222222 #BD93F9
        active_workspace   #222222 #222222 #FF79C6
        inactive_workspace #222222 #222222 #FF79C6
        urgent_workspace   #FF5555 #FF5555 #FF79C6
        binding_mode       #FF5555 #FF5555 #FF79C6
    }
}
