#!/bin/sh

volume() {
    vol="$(wpctl get-volume @DEFAULT_AUDIO_SINK@)"

    [ "$vol" != "${vol%\[MUTED\]}" ] && echo "M" && exit

    vol="${vol#Volume: }"

    vol="${vol/0./}"
    vol="${vol/1./1}"

    echo "$vol%"
}

batt() {
    cat /sys/class/power_supply/BAT1/capacity
}

clock() {
    date +'%b %d %H:%M'
}

network() {
    iw dev wlp192s0 info | awk '/ssid/ { printf $2 }' || echo "disconnected"
}


echo "{\"version\": 1, \"click_events\": true}"

echo [
while cat << EOF; do
[
    {
        "name": "network",
        "full_text": "wlan: $(network)"
    },
    {
        "name": "volume",
        "full_text": "vol: $(volume)"

    },
    {
        "name": "battery",
        "full_text": "batt: $(batt)%"
    },
    {
        "name": "clock",
        "full_text": "$(clock)"
    }
],
EOF
    sleep 1;
done &

while read click
do
    module="$(echo $click | awk -F \" '{ printf $4 }')"
    echo $module >> /home/eepy/swaybarin
    [ "$module" = "volume" ] && pavucontrol
    [ "$module" = "network" ] && nm-connection-editor

done < "${1:-/dev/stdin}"
