#!/bin/sh

volume() {
    vol="$(wpctl get-volume @DEFAULT_AUDIO_SINK@)"

    [ "$vol" != "${vol%\[MUTED\]}" ] && echo "M" && exit

    vol="${vol#Volume: }"

    vol="${vol/0./}"
    vol="${vol/1./1}"

    echo "$vol%"
}

batt() {
    cat /sys/class/power_supply/BAT1/capacity
}

clock() {
    date +'%b %d %H:%M'
}

network() {
    iw dev wlp192s0 info | awk '/ssid/ { printf $2 }' || echo "disconnected"
}

vpn() {
    connection="$(mullvad status | awk '/Relay/ { printf $2 }')"
    [ "$connection" ] && echo "$connection" || echo "disconnected"
}

echo "{\"version\": 1, \"click_events\": true}"

echo [
while true; do
    cat << EOF
[
    {
        "name": "vpn",
        "full_text": "vpn: $(vpn)"
    },
    {
        "name": "network",
        "full_text": "wlan: $(network)"
    },
    {
        "name": "volume",
        "full_text": "vol: $(volume)"

    },
    {
        "name": "battery",
        "full_text": "batt: $(batt)%"
    },
    {
        "name": "clock",
        "full_text": "$(clock)"
    }
],
EOF
    sleep 1;
done &

while read click
do
    module="$(echo $click | awk -F \" '{ printf $4 }')"
    #echo $module >> /home/eepy/swaybarin
    case $module in
        "volume")
            pavucontrol
            ;;
        "network")
            nm-connection-editor
            ;;
        "vpn")
            /opt/Mullvad\ VPN/mullvad-gui
            ;;
    esac


done < "${1:-/dev/stdin}"
